brew "nvim"
brew "ripgrep"
brew "fd"
brew "lazygit"
brew "trash"
brew "tmux"
brew "tmuxinator"
brew "ffmpeg"
brew "direnv"
cask "wezterm"

# --------------------- #
# python
# --------------------- #
brew "pyenv"
brew "pyenv-virtualenv"
brew "poetry"

# --------------------- #
# volta
# --------------------- #
brew "volta"


# --------------------- #
# react native
# --------------------- #
brew "watchman"

# --------------------- #
# fonts
# --------------------- #
cask "font-monaspace-nerd-font"

# --------------------- #
# browser
# --------------------- #
cask "arc"
cask "google-chrome"

# --------------------- #
# Docker
# --------------------- #
cask "docker"
brew "docker-compose"


# --------------------- #
# Rust
# --------------------- #
brew "rustup-init"


# --------------------- #
# Dev GUI tools
# --------------------- #
cask "alfred"
cask "clipy"
cask "hammerspoon"
cask "hyperkey"
cask "alt-tab"


# --------------------- #
# Other tools
# --------------------- #
cask "spotify"
