# CLI tools
brew "direnv"
brew "watchman"
brew "eza"
brew "trash"
brew "bat"
brew "jq"
brew "peco" # for ccc
brew "hunk"
brew "yt-dlp"

# PDF / 図版
brew "ghostscript" # `gs`
brew "poppler"     # `pdftotext` `pdfinfo`
brew "graphviz"    # `dot`

# macOS apps
cask "hyperkey"
cask "alfred"
cask "clipy"
cask "alt-tab"
cask "spotify"
cask "iina"
cask "slack"
cask "figma"
cask "opensuperwhisper"
cask "ticktick"
cask "drawio"
cask "mark-text"
