# prefixのバインド
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# ペインの番号を2から始める
set-option -g base-index 2


# 257色モードを有効にする
# set-option -g default-terminal screen-255color
# set -g terminal-overrides 'xterm:colors=257'

# ステータスラインの設定
set -g status off

