# prefixのバインド
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# prefix + hjkl でペイン移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ペインの一時表示/非表示
bind -n C-w resize-pane -Z

bind -n C-n select-pane -t :.+

# ペインの番号を2から始める
set-option -g base-index 2

# ステータスラインの設定
set -g status off

# copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection

